"use server";

import { ai } from "@/lib/gemini";
import { resumeAnalysisPrompt } from "@/lib/prompts/resume-analysis";

import { connectDB } from "@/lib/mongodb";

import { syncUser } from "./user.actions";

import Application from "@/models/Application";
import Resume from "@/models/Resume";
import Analysis from "@/models/Analysis";

import { serialize } from "@/types/action";

/* =========================================================
   HELPER
========================================================= */

function extractJson(text: string) {
  try {
    return JSON.parse(text);
  } catch {
    const cleaned = text
      .replace(/```json/g, "")
      .replace(/```/g, "")
      .trim();

    return JSON.parse(cleaned);
  }
}

/* =========================================================
   ANALYZE RESUME
========================================================= */

export async function analyzeResume(applicationId: string) {
  try {
    await connectDB();

    const user = await syncUser();

    if (!user.success || !user.data) {
      return {
        success: false,
        message: "Unauthorized",
      };
    }

    /* -------------------------------------------------------
       FIND APPLICATION
    ------------------------------------------------------- */

    const application = await Application.findOne({
      _id: applicationId,
      userId: user.data._id,
    });

    if (!application) {
      return {
        success: false,
        message: "Application not found.",
      };
    }

    /* -------------------------------------------------------
       CHECK RESUME
    ------------------------------------------------------- */

    if (!application.resumeId) {
      return {
        success: false,
        message: "Resume not selected.",
      };
    }

    const resume = await Resume.findById(application.resumeId);

    if (!resume) {
      return {
        success: false,
        message: "Resume not found.",
      };
    }

    /* =======================================================
       DOWNLOAD RESUME PDF
    ======================================================= */

    const fileResponse = await fetch(resume.url);

    if (!fileResponse.ok) {
      return {
        success: false,
        message: "Unable to download resume.",
      };
    }

    const arrayBuffer = await fileResponse.arrayBuffer();

    const pdfBase64 = Buffer.from(arrayBuffer).toString("base64");

    /* =======================================================
       ASK GEMINI
    ======================================================= */

    const geminiResponse = await ai.models.generateContent({
      model: "gemini-flash-latest",

      contents: [
        {
          inlineData: {
            mimeType: "application/pdf",
            data: pdfBase64,
          },
        },

        {
          text: `
${resumeAnalysisPrompt}

Job Description

${application.jobDescription}
`,
        },
      ],
    });

    const responseText = geminiResponse.text?.trim();

    if (!responseText) {
      return {
        success: false,
        message: "Gemini returned an empty response.",
      };
    }

    /* =======================================================
       PARSE GEMINI RESPONSE
    ======================================================= */

    let result: any;

    try {
      result = extractJson(responseText);
    } catch (error) {
      console.error("Gemini JSON Parse Error");
      console.log(responseText);

      return {
        success: false,
        message: "Unable to parse AI response.",
      };
    }

    /* =======================================================
       VALIDATE AI RESPONSE
    ======================================================= */

    if (
      !result.resumeHealth ||
      !result.atsAnalysis ||
      !result.jobMatch ||
      !result.sectionReview
    ) {
      return {
        success: false,
        message: "Invalid analysis received from Gemini.",
      };
    }

    /* =======================================================
       CREATE ANALYSIS
       
       createdAt will be automatically generated by Mongoose
       if timestamps: true is enabled in Analysis schema.
    ======================================================= */

    const analysis = await Analysis.create({
      userId: user.data._id,

      applicationId: application._id,

      resumeId: resume._id,

      company: application.company,

      jobTitle: application.jobTitle,

      location: application.location,

      appliedDate: application.appliedDate,

      status: application.status,

      resumeName: resume.fileName,

      resumeUrl: resume.url,

      jobDescription: application.jobDescription,

      analysisTitle: `${application.company} - ${application.jobTitle}`,

      analysisResult: result,
    });

    /* =======================================================
       UPDATE APPLICATION STATUS
    ======================================================= */

    await Application.findByIdAndUpdate(application._id, {
      status: "Ready to Apply",
    });

    /* =======================================================
       RETURN
    ======================================================= */

    return {
      success: true,
      data: serialize(analysis),
    };
  } catch (error) {
    console.error("Gemini Analysis Error:", error);

    return {
      success: false,
      message: "Gemini analysis failed.",
    };
  }
}

/* =========================================================
   GET ANALYSIS BY ID
========================================================= */

export async function getAnalysisById(id: string) {
  try {
    await connectDB();

    const user = await syncUser();

    if (!user.success || !user.data) {
      return {
        success: false,
        message: "Unauthorized",
      };
    }

    const analysis = await Analysis.findOne({
      _id: id,
      userId: user.data._id,
    });

    if (!analysis) {
      return {
        success: false,
        message: "Analysis not found.",
      };
    }

    return {
      success: true,
      data: serialize(analysis),
    };
  } catch (error) {
    console.error("Get Analysis Error:", error);

    return {
      success: false,
      message: "Unable to fetch analysis.",
    };
  }
}

/* =========================================================
   GET USER ANALYSIS HISTORY
========================================================= */

export async function getUserAnalysisHistory({
  search = "",
  company = "",
  score = "",
  date = "",
  sort = "latest",
  page = 1,
  limit = 10,
}: {
  search?: string;
  company?: string;
  score?: string;
  date?: string;
  sort?: string;
  page?: number;
  limit?: number;
}) {
  try {
    await connectDB();

    /* =======================================================
       AUTHENTICATION
    ======================================================= */

    const user = await syncUser();

    if (!user.success || !user.data) {
      return {
        success: false,
        data: [],
        pagination: {
          page: 1,
          limit,
          totalItems: 0,
          totalPages: 0,
        },
        message: "Unauthorized",
      };
    }

    /* =======================================================
       NORMALIZE PAGINATION
    ======================================================= */

    const currentPage = Math.max(1, Number.isInteger(page) ? page : 1);

    const pageLimit = Math.min(
      50,
      Math.max(1, Number.isInteger(limit) ? limit : 10),
    );

    /* =======================================================
       BASE QUERY
    ======================================================= */

    const query: any = {
      userId: user.data._id,
    };

    /* =======================================================
       SEARCH
       
       Search by:
       - Company
       - Job Title
    ======================================================= */

    const trimmedSearch = search.trim();

    if (trimmedSearch) {
      query.$or = [
        {
          company: {
            $regex: trimmedSearch,
            $options: "i",
          },
        },

        {
          jobTitle: {
            $regex: trimmedSearch,
            $options: "i",
          },
        },
      ];
    }

    /* =======================================================
       COMPANY FILTER
    ======================================================= */

    const trimmedCompany = company.trim();

    if (trimmedCompany) {
      query.company = {
        $regex: trimmedCompany,
        $options: "i",
      };
    }

    /* =======================================================
       SCORE FILTER
    ======================================================= */

    switch (score) {
      case "0-50":
        query["analysisResult.atsAnalysis.atsScore"] = {
          $gte: 0,
          $lt: 50,
        };
        break;

      case "50-70":
        query["analysisResult.atsAnalysis.atsScore"] = {
          $gte: 50,
          $lt: 70,
        };
        break;

      case "70-90":
        query["analysisResult.atsAnalysis.atsScore"] = {
          $gte: 70,
          $lt: 90,
        };
        break;

      case "90-100":
        query["analysisResult.atsAnalysis.atsScore"] = {
          $gte: 90,
          $lte: 100,
        };
        break;

      default:
        // No score filter
        break;
    }

    /* =======================================================
       DATE FILTER
       
       IMPORTANT:
       Use createdAt, NOT analyzedAt.
       
       The AnalysisTable also uses:
       
       analysis.createdAt
       
       So both sides now use the same field.
    ======================================================= */

    if (date) {
      /*
        Input from <input type="date"> is:

        YYYY-MM-DD

        We create the beginning and end of that day.
      */

      const start = new Date(`${date}T00:00:00.000`);

      const end = new Date(`${date}T23:59:59.999`);

      query.createdAt = {
        $gte: start,
        $lte: end,
      };
    }

    /* =======================================================
       SORTING
    ======================================================= */

    let sortQuery: any;

    switch (sort) {
      case "oldest":
        sortQuery = {
          createdAt: 1,
        };
        break;

      case "highest":
        sortQuery = {
          "analysisResult.atsAnalysis.atsScore": -1,

          /*
            Secondary sorting ensures stable ordering
            when two analyses have the same score.
          */
          createdAt: -1,
        };
        break;

      case "lowest":
        sortQuery = {
          "analysisResult.atsAnalysis.atsScore": 1,

          createdAt: -1,
        };
        break;

      case "latest":
      default:
        sortQuery = {
          createdAt: -1,
        };
        break;
    }

    /* =======================================================
       PAGINATION
    ======================================================= */

    const skip = (currentPage - 1) * pageLimit;

    /* =======================================================
       TOTAL COUNT
    ======================================================= */

    const totalItems = await Analysis.countDocuments(query);

    const totalPages = totalItems === 0 ? 0 : Math.ceil(totalItems / pageLimit);

    /* =======================================================
       FETCH ANALYSES
    ======================================================= */

    const analyses = await Analysis.find(query)
      .sort(sortQuery)
      .skip(skip)
      .limit(pageLimit)
      .lean();

    /* =======================================================
       RETURN PAGINATED DATA
    ======================================================= */

    return {
      success: true,

      data: serialize(analyses),

      pagination: {
        page: currentPage,

        limit: pageLimit,

        totalItems,

        totalPages,
      },
    };
  } catch (error) {
    console.error("Get Analysis History Error:", error);

    return {
      success: false,

      data: [],

      pagination: {
        page: 1,
        limit,
        totalItems: 0,
        totalPages: 0,
      },

      message: "Unable to fetch analyses.",
    };
  }
}
